CREATE TABLE IF NOT EXISTS films {
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    film_name varchar(250) NOT NULL,
    description varchar(200) NOT NULL,
    releaseDate date NOT NULL,
    duration INTEGER NOT NULL,
    mpa_id INTEGER NOT NULL REFERENCES mpa_rating (mpa_id) ON DELETE CASCADE
};

CREATE TABLE IF NOT EXISTS users {
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email varchar(40) NOT NULL,
    login varchar(40) NOT NULL UNIQUE,
    user_name varchar(40),
    birthday date NOT NULL
};

CREATE TABLE IF NOT EXISTS friends {
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE NOT NULL,
    friend_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (user_id, friend_id)
};

CREATE TABLE IF NOT EXISTS film_genres {
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE NOT NULL,
    genre_id INTEGER REFERENCES genres (genre_id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (film_id, genre_id)
};

CREATE TABLE IF NOT EXISTS mpa_rating {
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    mpa_ name varchar(40) NOT NULL
};

CREATE TABLE IF NOT EXISTS likes {
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (film_id, user_id)
};

CREATE TABLE IF NOT EXISTS genres {
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    genre_name varchar(40) NOT NULL
};




